- name: ensure PHP installed
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-dev
    - php5-cli
    - php5-intl
    - php5-json
    - php5-pgsql
    - php5-mysql
    - php5-sqlite
    - php5-curl
    - php5-gd
    - php5-mcrypt
    - php5-memcached
  tags: php

- name: configure PHP settings
  template: src=php.ini dest=/etc/php5/mods-available/custom.ini
  notify:
    - restart apache2
  tags: php

- name: enable PHP config
  file: src=/etc/php5/mods-available/custom.ini dest=/etc/php5/apache2/conf.d/custom.ini state=link
