---
- hosts: vagrant
  sudo: true
  vars_files:
    - defaults/variables.yml

  roles:
    - initial
    - common
    - apache
    - php
    - composer
    - memcached
    - sqlite
    - mysql
    - phpmyadmin
    - adminer
    - yii-advanced-project
